apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         10
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        tls On
        tls.verify Off

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-loki.conf

  # The default configmap assumes that dockershim is utilized for the cluster. If a CRI runtime, such as containerd or CRI-O, is being utilized, the CRI parser should be utilized.
  # More specifically, change the Parser described in input-kubernetes.conf from docker to cri.
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.app.*
        Path              /var/log/containers/spring-*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Skip_Long_Lines   On
        Refresh_Interval  30

    [INPUT]
        Name              tail
        Tag               kube.sys.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/spring-*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Skip_Long_Lines   On
        Refresh_Interval  30


  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.app.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.app.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                kubernetes
        Match               kube.sys.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.sys.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  output-loki.conf: |
    [OUTPUT]
        name                   loki
        match                  kube.app.*
        host                   loki
        port                   3100
        labels                 source=app, severity=$message['severity'], application_name=$kubernetes['labels']['app.kubernetes.io/name'], pod_name=$kubernetes['pod_name']
        auto_kubernetes_labels off

    [OUTPUT]
        name                   loki
        match                  kube.sys.*
        host                   loki
        port                   3100
        labels                 source=sys, pod_name=$kubernetes['pod_name']
        auto_kubernetes_labels off

  parsers.conf: |
    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Decode_Field_As    json     message
