apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jaeger
subsets:
  - addresses:
      - ip: 192.168.1.176
    ports:
      - port: 9411