apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-monitoring-b
  labels:
    app.kubernetes.io/name: spring-monitoring-b
    environment: develop
    cluster: vd

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-monitoring-b
  template:
    metadata:
      namespace: default
      labels:
        app.kubernetes.io/name: spring-monitoring-b
    spec:
      containers:
        - name: spring-monitoring-b
          image: ntuveri/spring-monitoring:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
      restartPolicy: Always